enum ErrorType
{
  SYNTAX_ERROR = 1,

  MISSING_KEYWORD_BEGIN,
  MISSING_KEYWORD_CALL,
  MISSING_KEYWORD_CONST,
  MISSING_KEYWORD_DO,
  MISSING_KEYWORD_END,
  MISSING_KEYWORD_ELSE,
  MISSING_KEYWORD_FOR,
  MISSING_KEYWORD_IF,
  MISSING_KEYWORD_ODD,
  MISSING_KEYWORD_PROCEDURE,
  MISSING_KEYWORD_PROGRAM,
  MISSING_KEYWORD_THEN,
  MISSING_KEYWORD_TO,
  MISSING_KEYWORD_VAR,
  MISSING_KEYWORD_WHILE,

  MISSING_PUNCTUATION_LEFT_PARENTHESIS,
  MISSING_PUNCTUATION_RIGHT_PARENTHESIS,
  MISSING_PUNCTUATION_LEFT_BRACKET,
  MISSING_PUNCTUATION_RIGHT_BRACKET,
  MISSING_PUNCTUATION_COMMA,
  MISSING_PUNCTUATION_SEMICOLON,
  MISSING_PUNCTUATION_PERIOD,
  MISSING_PUNCTUATION_EQUAL,

  MISSING_OPERATOR_ASSIGN,

  MISSING_OPERAND = 30,

  MISSING_PROGRAM_NAME,
  MISSING_CONSTANT_NAME,
  MISSING_VARIABLE_NAME,
  MISSING_PROCEDURE_NAME,

  MISSING_RANGE_NUMBER,
  MISSING_PARAMETER_NAME,
  NUMBER_EXCEED_LIMIT,

};